### ISSUE TITLE
Homework 2 Feedback

### ISSUE THREAD

**Issue by HeyStenson** [jaeness/resume_wendy_g_bite#1]
Well done! :palm_tree: 

**Readability of your code (1-3):**
3
**Does it run? (1-3):**
3
**Are best practices followed? (1-3):**
2

**Notes:**
- Look again at the example image, and you’ll notice that the document uses two separate fonts. How can you use CSS to get this effect?
- Think about the DRY principle (Don’t Repeat Yourself). If most of the text on the page is white, you can just declare it once at the body level and then adjust it in later elements as needed.
- On lines 63 and in your CSS, you set `text-align: left;`. The default is actually left, so you don’t need to declare this.

**Comment by jaeness** [comment]
HI There, Is 3 the best and 1 is worst?  Also, may I please ask you to walk me through the feedback tomorrow?  Thank you!

**Comment by HeyStenson** [comment]
Yep, 3 is perfect, 2 is good, and 1 needs some work. And yes, we can absolutely go over this during office hours tonight. :smile:

**Comment by jaeness** [comment]
Hi There,

I am advising one of our classmates on Product Management so I will not be
able to make class hours.  May we do Thursday?  Looking forward to improve
with your guidance.

Best,
Jaemi

**Comment by HeyStenson** [comment]
Yes, we can certainly cover it on Thursday! Are you going to just be missing office hours today, or the whole class?

**Comment by jaeness** [comment]
just office hours.  I will be there for the whole class.  I really love it
and learning a ton.

**Comment by HeyStenson** [comment]
Awesome, see you then!

On Tue, Apr 12, 2016 2:18 PM, Jaemi Bremner notifications@github.com wrote:
just office hours. I will be there for the whole class. I really love it
and learning a ton.
